[mgr]
show_hidden = true
sort_by = "natural"

[opener]
# Custom openers to add to defaults
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]

pdf = [
    { run = 'zathura "$@"', desc = "Zathura", orphan = true, for = "unix" },
]

office = [
    { run = 'libreoffice "$@"', orphan = true, for = "unix" },
]

extract = [
    { run = 'ouch d -y "$@"', desc = "Extract here", for = "unix" },
]

# Default fallback opener for files without extensions or unknown types
default = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]

[open]
# Prepend custom rules to the default rules
prepend_rules = [
    # Programming files - prefer nvim over default text editor
    { name = "*.{py,rs,c,cpp,h,hpp,js,ts,html,css,sh,bash,zsh,lua,go,java,kt}", use = ["edit"] },
    
    # Configuration files - prefer nvim
    { name = "*.{json,yaml,yml,toml,xml,cfg,conf,ini,md,txt,log}", use = ["edit"] },
    
    # Office documents
    { name = "*.{docx,pptx,xlsx,odt,ods,odp}", use = ["office"] },
    
    # PDFs with custom viewer
    { name = "*.pdf", use = ["pdf"] },
    
    # Archives with custom extractor
    { name = "*.{zip,tar,gz,bz2,xz,7z,rar}", use = ["extract"] },
]

# Append fallback rule after all default rules
append_rules = [
    # Fallback for files without extensions or unknown types
    { name = "*", use = ["default"] },
]

[confirm]
trash = false
delete = true

[plugin]
prepend_previewers = [
    # Archive previewers
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]
